# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Attribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAttribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Attribute
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Attribute
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Attribute
    def BoolValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Attribute
    def Int32Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Attribute
    def Uint32Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Attribute
    def Float32Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Attribute
    def StringValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Attribute
    def Unk6(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Attribute
    def Unk6AsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # Attribute
    def Unk6Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Attribute
    def Unk6IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # Attribute
    def ByteList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Attribute
    def ByteListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # Attribute
    def ByteListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Attribute
    def ByteListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # Attribute
    def Int32List(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Attribute
    def Int32ListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Attribute
    def Int32ListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Attribute
    def Int32ListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # Attribute
    def Float32List(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Attribute
    def Float32ListAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Attribute
    def Float32ListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Attribute
    def Float32ListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # Attribute
    def Unk10(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Attribute
    def Unk10AsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # Attribute
    def Unk10Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Attribute
    def Unk10IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # Attribute
    def Attributes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from flatbuffer.Attribute import Attribute
            obj = Attribute()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Attribute
    def AttributesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Attribute
    def AttributesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

def AttributeStart(builder):
    builder.StartObject(13)

def Start(builder):
    AttributeStart(builder)

def AttributeAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    AttributeAddName(builder, name)

def AttributeAddType(builder, type):
    builder.PrependUint8Slot(1, type, 0)

def AddType(builder, type):
    AttributeAddType(builder, type)

def AttributeAddBoolValue(builder, boolValue):
    builder.PrependBoolSlot(2, boolValue, 0)

def AddBoolValue(builder, boolValue):
    AttributeAddBoolValue(builder, boolValue)

def AttributeAddInt32Value(builder, int32Value):
    builder.PrependInt32Slot(3, int32Value, 0)

def AddInt32Value(builder, int32Value):
    AttributeAddInt32Value(builder, int32Value)

def AttributeAddUint32Value(builder, uint32Value):
    builder.PrependUint32Slot(4, uint32Value, 0)

def AddUint32Value(builder, uint32Value):
    AttributeAddUint32Value(builder, uint32Value)

def AttributeAddFloat32Value(builder, float32Value):
    builder.PrependFloat32Slot(5, float32Value, 0.0)

def AddFloat32Value(builder, float32Value):
    AttributeAddFloat32Value(builder, float32Value)

def AttributeAddStringValue(builder, stringValue):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(stringValue), 0)

def AddStringValue(builder, stringValue):
    AttributeAddStringValue(builder, stringValue)

def AttributeAddUnk6(builder, unk6):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(unk6), 0)

def AddUnk6(builder, unk6):
    AttributeAddUnk6(builder, unk6)

def AttributeStartUnk6Vector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartUnk6Vector(builder, numElems):
    return AttributeStartUnk6Vector(builder, numElems)

def AttributeCreateUnk6Vector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependInt8(item)
    return builder.EndVector()

def CreateUnk6Vector(builder, data):
    AttributeCreateUnk6Vector(builder, data)

def AttributeAddByteList(builder, byteList):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(byteList), 0)

def AddByteList(builder, byteList):
    AttributeAddByteList(builder, byteList)

def AttributeStartByteListVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartByteListVector(builder, numElems):
    return AttributeStartByteListVector(builder, numElems)

def AttributeCreateByteListVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependInt8(item)
    return builder.EndVector()

def CreateByteListVector(builder, data):
    AttributeCreateByteListVector(builder, data)

def AttributeAddInt32List(builder, int32List):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(int32List), 0)

def AddInt32List(builder, int32List):
    AttributeAddInt32List(builder, int32List)

def AttributeStartInt32ListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInt32ListVector(builder, numElems):
    return AttributeStartInt32ListVector(builder, numElems)

def AttributeCreateInt32ListVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependInt32(item)
    return builder.EndVector()

def CreateInt32ListVector(builder, data):
    AttributeCreateInt32ListVector(builder, data)

def AttributeAddFloat32List(builder, float32List):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(float32List), 0)

def AddFloat32List(builder, float32List):
    AttributeAddFloat32List(builder, float32List)

def AttributeStartFloat32ListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFloat32ListVector(builder, numElems):
    return AttributeStartFloat32ListVector(builder, numElems)

def AttributeCreateFloat32ListVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependFloat32(item)
    return builder.EndVector()

def CreateFloat32ListVector(builder, data):
    AttributeCreateFloat32ListVector(builder, data)

def AttributeAddUnk10(builder, unk10):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(unk10), 0)

def AddUnk10(builder, unk10):
    AttributeAddUnk10(builder, unk10)

def AttributeStartUnk10Vector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartUnk10Vector(builder, numElems):
    return AttributeStartUnk10Vector(builder, numElems)

def AttributeCreateUnk10Vector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependInt8(item)
    return builder.EndVector()

def CreateUnk10Vector(builder, data):
    AttributeCreateUnk10Vector(builder, data)

def AttributeAddAttributes(builder, attributes):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(attributes), 0)

def AddAttributes(builder, attributes):
    AttributeAddAttributes(builder, attributes)

def AttributeStartAttributesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAttributesVector(builder, numElems):
    return AttributeStartAttributesVector(builder, numElems)

def AttributeCreateAttributesVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateAttributesVector(builder, data):
    AttributeCreateAttributesVector(builder, data)

def AttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return AttributeEnd(builder)
