# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class DataType(object):
    INT8 = 8
    INT16 = 22
    INT32 = 50
    INT64 = 100
    UINT8 = 264
    UINT16 = 278
    UINT32 = 306
    UINT64 = 356
    FLOAT16 = 534
    FLOAT32 = 562
    QINT4 = 772
    QINT8 = 776
    QINT16 = 790
    QINT32 = 818
    QUINT4 = 1028
    QUINT8 = 1032
    QUINT16 = 1046
    QUINT32 = 1074
    BOOL = 1288
