# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ModelParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModelParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModelParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ModelParametersBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x45\x54\x50", size_prefixed=size_prefixed)

    # ModelParameters
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModelParameters
    def Nodes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from flatbuffer.NodeParameter import NodeParameter
            obj = NodeParameter()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelParameters
    def NodesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelParameters
    def NodesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ModelParametersStart(builder):
    builder.StartObject(1)

def Start(builder):
    ModelParametersStart(builder)

def ModelParametersAddNodes(builder, nodes):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(nodes), 0)

def AddNodes(builder, nodes):
    ModelParametersAddNodes(builder, nodes)

def ModelParametersStartNodesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNodesVector(builder, numElems):
    return ModelParametersStartNodesVector(builder, numElems)

def ModelParametersCreateNodesVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateNodesVector(builder, data):
    ModelParametersCreateNodesVector(builder, data)

def ModelParametersEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModelParametersEnd(builder)
