# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NodeParameter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NodeParameter()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNodeParameter(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def NodeParameterBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x45\x54\x50", size_prefixed=size_prefixed)

    # NodeParameter
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NodeParameter
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NodeParameter
    def Weights(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from flatbuffer.Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NodeParameter
    def WeightsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NodeParameter
    def WeightsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def NodeParameterStart(builder):
    builder.StartObject(2)

def Start(builder):
    NodeParameterStart(builder)

def NodeParameterAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    NodeParameterAddName(builder, name)

def NodeParameterAddWeights(builder, weights):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(weights), 0)

def AddWeights(builder, weights):
    NodeParameterAddWeights(builder, weights)

def NodeParameterStartWeightsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartWeightsVector(builder, numElems):
    return NodeParameterStartWeightsVector(builder, numElems)

def NodeParameterCreateWeightsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateWeightsVector(builder, data):
    NodeParameterCreateWeightsVector(builder, data)

def NodeParameterEnd(builder):
    return builder.EndObject()

def End(builder):
    return NodeParameterEnd(builder)
